### ISSUE TITLE
Using imports in python function

### ISSUE THREAD

**Issue by torphix** [meadowdata/meadowrun#267]
Hi Thanks for the awsome lib!

When executing a function can I seem unable to use imported libraries eg:
```
  
   def _inference_function(input_data):
            import os
           
            os.makedirs(f'/var/meadowrun/model_assets', exist_ok=True)

            return outputs

```
AttributeError: 'cell' object has no attribute 'makedirs' is the error im receiving

**Comment by kurtschelfthout** [comment]
'cell' object doesn't ring any bells at all...is `os` is somehow redefined as a variable in your code somewhere?

**Comment by torphix** [comment]
Thanks for getting back to, I was using python 3.10 in the github repo and specifying 3.9 in PipRequirements therefore was getting odd errors.
