### ISSUE TITLE
AWS limiting number of spot instances...

### ISSUE THREAD

**Issue by weisisheng** [meadowdata/meadowrun#84]
While trying out "poetry run python unzip_articles_on_cloud.py", the following error surfaces.

<snip>
botocore.exceptions.ClientError: An error occurred (MaxSpotInstanceCountExceeded) when calling the RunInstances operation: Max spot instance count exceeded
sys:1: RuntimeWarning: coroutine '_launch_instance_continuation' was never awaited
</snip>

Guessing the availability to access spot is extremely ephemeral.  Is there a fallback option?  Tried this at 12:30 a.m. EST on 7/3, us-west-2 on Ubuntu 22.04. 20 images were created.

Thanks!

**Comment by kurtschelfthout** [comment]
It is hitting a limit set by AWS in your account - especially if it’s a new one the limit is I believe fairly low. The idea is to avoid unexpected bills. 

https://stackoverflow.com/questions/43217134/aws-spot-instance-limit has some things you can check - if that helps please let us know as maybe we can automate some of those steps. 

You can also request a limit increase, some AWS docs: https://docs.aws.amazon.com/whitepapers/latest/cost-optimization-leveraging-ec2-spot-instances/spot-request-limits.html

Finally you can try on-demand instance by setting interruption_probability_threshold to 0, but that will be more expensive, and is also subject to similar on-demand instance limits on the AWS side. 

As usage increases on your EC2 account AWS increases limits as time goes on. 

All that said I do agree meadowrun could do better to deal with these kind of errors - eg it could fall back to on-demand if spot reaches some limit, but that’s currently not implemented.

**Comment by weisisheng** [comment]
Terrific and overwhelmingly complete advice.  I was running from a newish prod account so hitting limits.  Waiting on an increase approval and squeaking by trying the dev.to articles example code with 18 instances.  What a terrific application!  Look forward to learning more.  Thanks again.
