### ISSUE TITLE
More toy examples?

### ISSUE THREAD

**Issue by weisisheng** [meadowdata/meadowrun#97]
Are there any more code snippets for study by noobs to distributed instances text analysis? Thanks in advance.

**Comment by kurtschelfthout** [comment]
Not right now - we have some more plans for posts soon but they'll be demonstrating other kinds of usages, like training a ML model and testing. We may come back to text analysis in the future though.

**Comment by weisisheng** [comment]
Ok. let me know if I can help with proofreading instructional text or giving back in other ways.

**Comment by kurtschelfthout** [comment]
Thanks very much for the offer! Definitely any feedback on current docs/website or more generally what you're missing, like or don't like would be gratefully received.
